-- ID, SIZE --
SELECT ID,
-- CASE 구문 활용하기 --
    CASE WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
    WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
    ELSE 'HIGH'
    END AS SIZE
FROM ECOLI_DATA
-- ID 오름차순 --
ORDER BY ID
