-- 개수 세기 -> FISH_COUNT --
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I
-- 조인 시작 --
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
-- 조건 : BASS OR SNAPPER --
WHERE N.FISH_NAME = 'BASS' OR N.FISH_NAME = 'SNAPPER'