-- 성분 타입, 총주문량 조회 --
SELECT INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS HALF
-- 테이블 조인 --
JOIN ICECREAM_INFO AS INFO
ON HALF.FLAVOR = INFO.FLAVOR
-- 성분 타입 별로 그룹 묶어주기 --
GROUP BY INGREDIENT_TYPE
-- 총주문량이 작은 순서대로 조회 --
ORDER BY TOTAL_ORDER